### ISSUE TITLE
CLX' move to CLOS seems to have resulted in some implicit functions not being created.

### ISSUE THREAD

**Issue by earl-kent** [sharplispers/clx#104]
(ql version: clx-20180711-git) For every `xlib` 'class' that the the old `def-clx-class` macro used to create, a predicate function, e.g. `foo-p` would also be created unless it's creation was specifically suppressed in the class options.

```
(defmacro def-clx-class ((name &rest options) &body slots)
    ....
	  (when (eq predicate t)
	    (setf predicate (cintern name '-p)))
```
Some examples that used to work.

```
(xlib:window-p *application-window*)
(xlib:image-z-p  (xlib:get-image *application-window* :result-type 'image-xy :x x :y y :width width :height height))
(xlib:font-p (xlib:open-font *display* (first (xlib:list-font-names *display* "*"))))
```

**Comment by dkochmanski** [comment]
These predicates are documented in the manual and exported - should be readded as functions.
