### ISSUE TITLE
XKB troubles?

### ISSUE THREAD

**Issue by girzel** [sharplispers/clx#12]
My apologies if this is the right place to raise this question -- there aren't many venues for discussion of these issues!

I'm using the StumpWM CL window manager, I believe with this version of CLX, and the Xorg package that comes with Archlinux, currently at 1.15.2-1.

My issue is that, after setting the keyboard layout to colemak using setxkbmap, it is reset to qwerty the first time I switch windows. It happens every time I switch windows, and there seems to be nothing I can do to keep it on colemak.

The StumpWM people don't know what's going on, and it seemed unlikely that the Xorg folks would think it was their issue. So here I am! I would appreciate any tips you all might be able to provide, including simply pointers to more likely locations of the difficulty.

**Comment by dkochmanski** [comment]
Related to https://github.com/robert-strandh/McCLIM/issues/35

**Comment by dkochmanski** [comment]
in event-handler you have to call:

```
(when (eql event-key :mapping-notify)
    (return-from event-handler (xlib:mapping-notify display request 0 0)))
```

This invalidates the cache and fills it with new values.

**Comment by dkochmanski** [comment]
also see https://github.com/sharplispers/clx/issues/53
