### ISSUE TITLE
quicklisp cannot load clx on sbcl 

### ISSUE THREAD

**Issue by saufesma** [sharplispers/clx#121]
SBCL 1.3.14.debian

output
CL-USER> (ql:quickload :CLX)
To load "clx":
  Load 1 ASDF system:
    clx
; Loading "clx"

(:CLX)
CL-USER> (find-package 'CLX)
NIL

**Comment by PuercoPop** [comment]
that's because the package is named xlib, try `(find-package "XLIB")`

**Comment by saufesma** [comment]
cool, there it is
CL-USER> (find-package 'XLIB)
#<PACKAGE "XLIB">
let me see if my simple app works.

**Comment by saufesma** [comment]
My simple app does not like to run
No CLIM backends have been loaded!
   [Condition of type SIMPLE-ERROR]
And I can not find on the web how to deal with.
