### ISSUE TITLE
No CLIM backends have been loaded!

### ISSUE THREAD

**Issue by saufesma** [sharplispers/clx#122]
(in-package :common-lisp-user)

(defpackage "APP"
(:use :clim :clim-lisp)
(:export "APP-MAIN"))

(in-package :app)

(define-application-frame superapp ()
()
(:panes
(int :interactor :height 400 :width 600))
(:layouts
 (default int)))

(defun app-main ()
(run-frame-top-level (make-application-frame 'superapp)))

;;;To fire up
;;;in-package :app
 (app-main)

Couple of days ago the app was ok and oops today.

**Comment by saufesma** [comment]
CL-USER> climi::*server-path-search-order*
(:CLX :NULL)

**Comment by saufesma** [comment]
CL-USER> (find-package 'CLIM)
#<PACKAGE "CLIM">
CL-USER> (find-package 'CLIM-LISP)
#<PACKAGE "CLIM-LISP">

**Comment by saufesma** [comment]
May you tell me what did you remove for me to get an idea what cache means.

**Comment by dkochmanski** [comment]
`rm -rf ~/.cache/common-lisp`

I'm not asking if these packages are loaded but rather if you had loaded `mcclim` system, which pulls dependency on backends.

**Comment by saufesma** [comment]
I get the point. I issued
(ql:quicklisp 'clim)

instead of

(ql:quicklisp 'mcclim)

That was the problem.
Thanks

**Comment by saufesma** [comment]
When I try the following code
;;;;====McCLIM Guided Tour===========
(in-package :common-lisp-user)

(defpackage "HELLO"
(:use :clim :clim-lisp)
(:export "HELLO-MAIN"))

(in-package :hello)

(define-application-frame hello-world ()
  ((greeting :initform "Hello World"
         :accessor greeting))
  (:pane (make-pane 'hello-world-pane)))

(defclass hello-world-pane
  (clim-stream-pane) ())

;;; Behavior defined by the Handle Repaint Protocol
(defmethod handle-repaint ((pane hello-world-pane) region)
  (let ((w (bounding-rectangle-width pane))
    (h (bounding-rectangle-height pane)))
    ;; Blanc the pane out
    (draw-rectangle* pane 0 0 w h
             :filled t
             :ink (pane-background pane))
    ;; Draw greeting in center of pane
    (draw-text* pane
        (greeting *application-frame*)
        (floor w 2) (floor h 2)
        :align-x :center
        :align-y :center)))

(defun hello-main ()
(run-frame-top-level
 (make-application-frame 'hello-world)))

I have this output

There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLIM:IDENTITY-TRANSFORMATION-P (2)>
when called with arguments
  (NIL).
   [Condition of type SIMPLE-ERROR]

May you explain me what is going on.

**Comment by dkochmanski** [comment]
This is most likely a bug in McCLIM, please report a new issue in there. I'll take a look at it when I have a bit more time. I can reproduce the problem locally (and it doesn't look like there is anything wrong with your code).

**Comment by saufesma** [comment]
Already did. Why this happens to me.

**Comment by jiptohej** [comment]
(ql:quicklisp 'mcclim)
