### ISSUE TITLE
dbe backbuffer requires drawable to be a struct

### ISSUE THREAD

**Issue by rtoy** [sharplispers/clx#126]
In dbe.lisp, we have
```
(def-clx-class (back-buffer (:include drawable) (:copier nil)
			    (:print-function print-drawable)))
```

This requires `drawable` to be a structure.  But in depdefs.lisp, `*def-clx-class-use-defclass*` is not `nil` for cmucl.  I think everything else in clx would work (with some fixes) as is, but not dbe.

Not sure what the best approach is. I don't know why cmucl doesn't use nil for `*def-clx-class-use-defclass*`.

**Comment by dkochmanski** [comment]
this has been fixed with 623c33920c9c53212d1245493bf48a1e39a861ba
