### ISSUE TITLE
put-image problem with larger width

### ISSUE THREAD

**Issue by JMC-design** [sharplispers/clx#132]
While writing some display code for png-read and pngload I noticed that I could display a 8192x1024 png with put-image when it was loaded incorrectly by png-read as 1024x8192 but not when loaded correctly by pngload.
I have a suspicion the problem might lie with the index's

**Comment by dkochmanski** [comment]
could it be that your image can't be send to X11 server due to X11 request limit size? We already use big request extension, and if image doesn't fit then we send it scanline-by-scanline. If a single scanline doesn't fit in a request, then you are out of luck.

**Comment by JMC-design** [comment]
The big request extension isn't actually being used. I'm currently updating my testing environment now that you guys moved away from clos, before adapting and thoroughly testing the fix I've got.  It's not a big matter since 8k width is good enough for most people, however, it is the difference between put/get-image taking 254 requests or 1 to transfer FHD. I'm guessing Mcclim will probably be happy about that.
