### ISSUE TITLE
get-property ignores :result-type argument when there is no property.

### ISSUE THREAD

**Issue by PuercoPop** [sharplispers/clx#135]
For example

```lisp
STUMPWM> (xlib:get-property (window-xwin (current-window)) :WM_NORMAL_HINTSzz :type :WM_SIZE_HINTS :result-type 'vector)
NIL
NIL
0 (0 bits, #x0, #o0, #b0)
0 (0 bits, #x0, #o0, #b0)
```

given that we are asking for a vector I would expect the first value to be `#()` instead.

From what I see the was some code intended to support that
https://github.com/sharplispers/clx/blob/8c063b42f26259084f38718480f00e6cf0b9a03a/requests.lisp#L357

**Comment by JMC-design** [comment]
The protocol states that when the property doesn't exist none should be returned.  The first value is used in quite a few functions as a test.  Changing nil to an empty vector/string/list would affect all those, one example #'wm-normal-hints

**Comment by PuercoPop** [comment]
In CL its is customary for the existence of a value to be communicated in a separate return value, ej. [gethash](http://clhs.lisp.se/Body/f_gethas.htm). Ideally CLX should follow lisp conventions but as you mention not breaking existing code is more importancy

**Comment by dkochmanski** [comment]
In that case I'm closing this as a non-issue (documented behavior).
