### ISSUE TITLE
colormap class slot parameters loss?

### ISSUE THREAD

**Issue by yvm** [sharplispers/clx#137]
Attempt to xlib:create-colormap returned missing initarg error first and then missing setf for id slot. Bringing them back helped in my case. Not sure where these definitions in the repo.
```
(defclass colormap ()
  ((id :initarg :id :initform 0 :type resource-id
       :accessor colormap-id)
   (display :initarg :display :initform nil :type (or null display)
	    :reader colormap-display)
   (visual-info :initarg :visual-info :initform nil :type (or null visual-info)
		:accessor colormap-visual-info)))
```

**Comment by dkochmanski** [comment]
this was a regression fixed in 2018-12-03 when we have backed from switching to the standard-class. are you sure you have the newest ql release?
