### ISSUE TITLE
Limited image dimension support for put-raw-image

### ISSUE THREAD

**Issue by plops** [sharplispers/clx#14]
The function put-raw-image only allows to create XPutImage requests of a maximum length given by a 16-bit number. This corresponds e.g. to a 256x255x4 byte image and is quite limiting.

Bigger images could either be drawn using a multiple calls to XPutImage for sub-rectangles, or a single XPutImage request using the BIG-REQUESTS extension could be used. I think the first method is unnecessarily complicated. The latter I implemented in my own test code on https://github.com/plops/cl-pure-x11/blob/master/x.lisp This supports much larger images.

The function that constructs the request in my much more simple minded framework looks like this:

``` common-lisp
(defun put-image-big-req (img)
  (declare ((simple-array (unsigned-byte 8) 3) img))
  (destructuring-bind (h w c)
      (array-dimensions img)
   (let*((img1 (sb-ext:array-storage-vector img))
         (n (length img1))
         (p (pad n))) 
     (with-packet
       (card8 72)                       ; opcode
       (card8 2)                        ; format Z-pixmap
       (card16 0)                       ; length=0 => this is a big request
       (card32 (+ 7 (/ (+ n p) 4)))
       (card32 *window*)                ; window
       (card32 *gc*)
       (card16 w)
       (card16 h)
       (card16 0) ; dst-x
       (card16 0) ; dst-y
       (card8 0) ; left-pad
       (card8 24) ; depth
       (card16 0) ; unused
       )
     (write-sequence img1 *s*)
     (dotimes (i p)
       (write-byte 0 *s*))
     (force-output *s*))))
```

I tried to understand how CLX constructs its requests. Unfortunately I couldn't figure out how to write patch for CLX to create a request using a 32-bit length as the function above does.

**Comment by dkochmanski** [comment]
Rendering big pictures is already implemented as part of  `xrender` extension.
