### ISSUE TITLE
CMUCL supports CLX

### ISSUE THREAD

**Issue by rtoy** [sharplispers/clx#165]
Cmucl should support clx.  However, cmucl has historically supplied it's own copy, but a while back the cmucl version was replaced by this version of clx.  The last sync was to version 623c33920c9c53212d1245493bf48a1e39a861ba about a year ago.  This was included in cmucl version 21e.

**Comment by dkochmanski** [comment]
Is there something on CLX side what should be done? FWIW ECL also shipped its own version of CLX but it was removed from the repository in favor of this version (with expectancy that user will download the system if they need it).

**Comment by dkochmanski** [comment]
if you've meant the entry in readme, then I've just added entry for cmucl. if that's the case please close the issue.

**Comment by rtoy** [comment]
Yeah, it was readme, which suggested filing a bug.

I've debated about just letting users use quicklisp to download clx directly instead of maintaining a fork.  But maybe I can have it both ways by making cmucl's clx be a git subtree/submodule/subrepo so it stays in sync, more or less.
