### ISSUE TITLE
Any way to convert Compound Text to utf-8?

### ISSUE THREAD

**Issue by C-Entropy** [sharplispers/clx#180]
Since fcitx, a xorg client send compound text, we need to convert it to utf-8 manually. Is there any library for this?

**Comment by JMC-design** [comment]
Nope. Are you sure you can't request fcitx to send it in utf-8?
the encoding for compound text itself isn't very difficult to implement, i.e. reading which encoding to switch to.  It's the processing the text encodings after that.  I believe babel should be the place for this but they don't want anything to do with it but will accept prs.  I haven't had the time to figure out plugging into babel so nothing so far.

**Comment by C-Entropy** [comment]
Found Emacs's compound text [implementation](https://github.com/emacs-mirror/emacs/blob/4825ea3c5d067accad1e714531799f1836b548b5/lisp/international/mule.el#L1550)
Also, fcitx have enable utf-8.
