### ISSUE TITLE
xlib:put-raw-image doesn't check data size.

### ISSUE THREAD

**Issue by JMC-design** [sharplispers/clx#189]
xlib:put-raw-image does not behave like xlib:put-image.  It will not send the data in multiple requests. It wont even check if the data will fit in one request and so hangs with anything larger than max request size.
get-raw-image has the same deficiencies.

**Comment by dkochmanski** [comment]
`xlib:put-raw-image` is just a literal implementation of the x11 request. we should check for data size and signal an error, but splitting data into multiple requests is beyond the scope of this function.

For a nicer interface that splits requests see `xlib:put-image` that is build on top of the same x11 request but automates many things (like splitting the data).
