### ISSUE TITLE
Can't open Xquartz display

### ISSUE THREAD

**Issue by rpgoldman** [sharplispers/clx#19]
I'm not sure that this is actually a CLX bug.  Xquartz seems to use Unix sockets as the way to talk to the server.  After I start up Xquartz, the DISPLAY variable has a value like: /private/tmp/com.apple.launchd.EauNyeZmg1/org.macosforge.xquartz:0
which CLX chokes on (it thinks that the empty string before the leading "/" is a protocol spec and gets horribly confused).

AFAICT this syntax for a DISPLAY spec isn't legal: it doesn't seem to agree with the X spec. But it's not like I have an alternate X server I can use....

Anyone able to use this CLX on Mac?

**Comment by rpgoldman** [comment]
I pushed a topic branch, parse-xquartz-display to my fork of clx.  It uses one of Fare's UIOP implementation-independent functions to detect Mac OS X, and is heuristic about identifying sockets as value of DISPLAY, so it's quite possibly not ready for prime time.

This gets me through establishing contact with the server, but not successful authorization.

**Comment by rpgoldman** [comment]
Perhaps this is a different issue: `+X-unix-socket-path+` is a hard-coded path in CLX, but it seems that Xquartz uses different sockets dynamically. They should pass from the DISPLAY variable into `unix-socket-path-from-host`.

Looking at this, I'm having a little difficulty because it's not clear when `host` arguments really need to be hosts, and when they can be more general values (including a socket name).

**Comment by hydandata** [comment]
Bump, any chance one of these will get merged soon?

**Comment by dkochmanski** [comment]
I'm working on that right now

**Comment by dkochmanski** [comment]
@rpgoldman does #18 fix the issue, or it misses something from #21 ?

**Comment by rpgoldman** [comment]
I'm busy today, but I will try to test this on Monday.  I can test on a pretty wide variety of implementations.

**Comment by PuercoPop** [comment]
@dkochmanski btw I have a version of the PR #21 without all the extra whitespace changes (mantaining proper attribution) on https://github.com/PuercoPop/clx/commits/pr-21. There are some non-trivial merge conflicts with the pr #18 from what I recall

**Comment by dkochmanski** [comment]
Sounds good, if @rpgoldman 's tests fill fail, we'll try to merge it (we may try to revert #18 and apply this). If all tests will proof OK, I'll close this issue and #21 as fixed.

**Comment by rpgoldman** [comment]
`XLIB:OPEN-DEFAULT-DISPLAY` now works for me in SBCL on Mac OS X. I will test on other implementations.

**Comment by rpgoldman** [comment]
Works on CCL as well, but not on ACL, but that's because of #45 for now.  ECL fails.

**Comment by dkochmanski** [comment]
ECL fails because CLX doesn't work on ECL (it has its own version). That said I want to change this state (port CLX to ECL and get rid of the bundled version).
