### ISSUE TITLE
`buffer-read-default` should return non-`NIL`, non-`:TIMEOUT` on EOF on CMU, SBCL, ECL, CLISP, and CLASP

### ISSUE THREAD

**Issue by abridgewater** [sharplispers/clx#200]
Per the generic implementation (below the platform-specific implementations) in `dependent.lisp`, and clearly tested by the logic in `input.lisp`, end-of-file on the display connection should cause `buffer-read-default` to return a value that is neither `NIL` nor `:TIMEOUT`. Failing to so do causes an END-OF-FILE error to be signaled when the server connection is closed (such as via a KillClient request issued by a window manager when closing a window that doesn't participate in the WM_DELETE_WINDOW protocol).

This was also clearly handled by `minima`, `lcl3.0`, `genera`, and `explorer` in earlier releases of CLX.

**Comment by dkochmanski** [comment]
Fixed in #205. Thank you for the report and proposed solution.
