### ISSUE TITLE
Maybe release a new version

### ISSUE THREAD

**Issue by MIvanchev** [sharplispers/clx#207]
Hey, thank you for continuing the work on CLX, I use it daily and appreciate it very much! I've submitted a StumpWM package for Void Linux and https://github.com/void-linux/void-packages/pull/49434 and noticed the CLX version is quite old and quite some commits were added since the release. Maybe you could tag and release a new version?

**Comment by dkochmanski** [comment]
good idea, fixed!

**Comment by MIvanchev** [comment]
Thank you Daniel!
