### ISSUE TITLE
.Xauthority prevents X11 from starting

### ISSUE THREAD

**Issue by dbjergaard** [sharplispers/clx#24]
A user has reported a crash involving an authentication error preventing StumpWM from starting.  A full back trace indicates that the problem is in CLX's handling of authenticating a session.  

Further details here:
https://github.com/stumpwm/stumpwm/issues/239

Let me know if you need anything else.  I don't have a minimal working example, but could invest some effort if needed.

**Comment by jorams** [comment]
Note that #23 is about the same issue.

**Comment by dkochmanski** [comment]
this seems to be fixed. Closing for now.
