### ISSUE TITLE
clash with cl-opengl

### ISSUE THREAD

**Issue by chuchana** [sharplispers/clx#29]
`CLX` clashes with `cl-opengl` because CLX defines a `gl` package and cl-opengl nicknames the package cl-opengl with the name gl.

@cbaggers suggested that having CLX depend on cl-opengl could make sense to resolve this.

[https://github.com/cbaggers/cepl/issues/56]

**Comment by cbaggers** [comment]
Just to clarify, I havent checked if it is feasible. But it's a bummer that we have this clash.
If CLX's GL package is just bindings around opengl then this is well services by cl-opengl and it would be good to see what could be shared.

**Comment by PuercoPop** [comment]
A simpler solution would be to rename the gl package to something like xlib-gl (and glx to xlib-glx) for consistency. Not being able to load clx and cl-opengl in the same image is an important issue

**Comment by dkochmanski** [comment]
@chuchana problem is that both gl packages export different sets of symbols (cl-opengl has nicer api)
@PuercoPop what about breaking other packages? Do we know how many applications depend on clx's GL?

**Comment by luismbo** [comment]
FWIW, @3b created https://github.com/3b/package-local-nicknames for this use case. The idea would be that both cl-opengl and clx would drop their gl nicknames and each using package with declare the `gl` package-local nickname. Until that gets traction, perhaps the one with fewer users could drop the gl? :-)

**Comment by dkochmanski** [comment]
I think it's a good idea rename `gl` to `xlib.gl` and `glx` to `xlib.glx` (xinerama started a convention with dot in clx – "XLIB.XINERAMA", that's also in spirit of hierarchical packages)

**Comment by luismbo** [comment]
I like `/` better, but `.` works fine. :-)

**Comment by luismbo** [comment]
@sharplispers/owners anybody object to renaming `gl` to `xlib.gl` (or `xlib/gl`, or whatever)?

**Comment by dkochmanski** [comment]
I'd rather want somebody to peer review if I didn't do something stupid (I've renamed all packages to match one convention)
