### ISSUE TITLE
Start a test suite

### ISSUE THREAD

**Issue by tarballs-are-good** [sharplispers/clx#41]
For something standardized like X, and for complex software projects in general, and especially for dynamically typed languages like Lisp, there ought to be a test suite.

Making test suites is big, complicated, and—to most—boring. But their existence is a basic tenet of good software.

Making a test suite for something graphical+networked is especially difficult.

Some initial steps:
- [x] Pick a test framework. I'm partial to Fiasco. Many like FiveAM however.
- [x] Add clx-test.asd and subsume currently existing test directory for test source code.
- [x] Organize tests by sections of the standard being implemented, as well as auxiliary tests for (a) implementation-specific things and (b) utility/scaffolding/etc. code.

**Comment by luismbo** [comment]
I'm partial to Fiasco as well. :-)

Sounds like Xvfb could be very useful for this test suite you propose. We can use it to run CLX code and grab screenshot at key points, comparing them to pre-recorded screenshots. (Some tests might not require screenshot at all, of course.)

**Comment by tarballs-are-good** [comment]
Xvfb can even be used to just check that interactions aren't causing errors. Some links: [general info](https://en.wikipedia.org/wiki/Xvfb), [taking screenshots](http://semicomplete.com/blog/geekery/xvfb-firefox.html)

**Comment by dkochmanski** [comment]
so we may agree, that `fiasco` is our testing framework and mark the first step as done?

**Comment by dkochmanski** [comment]
I have a disciple who wants to contribute (in order to learn), I'll let him handle creating the system

**Comment by uint** [comment]
I'm poking at Fiasco currently, half-pondering this issue.

Is there any reason the test system should be defined in a separate file and not simply in the existing `clx.asd` one?

What do you think about the following infrastructure as a starting point? Say there's a top-level `test.lisp` file with some very basic code for defining test suites and keeping track of them (it doesn't seem Fiasco handles this sort of hierarchy gracefully enough by itself and needs a little help, unless I'm missing something). Then there's also a `tests` directory, where each file defines a single test suite.

**Comment by rpgoldman** [comment]
You should be able to define "clx/test" as the test system in clx.asd, and hook it up via 
```
:in-order-to ((test-op (test-op "clx/test")))
```
in the definition of the `clx` system.

**Comment by dkochmanski** [comment]
we've integrated fiasco framework into the codebase. that marks second point as completed.

**Comment by dkochmanski** [comment]
`Chapter 3: Displays` test suite: https://github.com/sharplispers/clx/pull/87

**Comment by tarballs-are-good** [comment]
The new Fiasco code should be merged in

**Comment by dkochmanski** [comment]
@uint could you take care of that? (merging Fiasco code)

**Comment by dkochmanski** [comment]
I think that the part about "starting" the test suite is finished. Please reopen the ticket if you disagree.
