### ISSUE TITLE
Compile time problem on Allegro

### ISSUE THREAD

**Issue by rpgoldman** [sharplispers/clx#48]
Allegro crashes trying to compile this CLX, with the following error:

```
attempt to call `XLIB::EXTENSION-EVENT-KEY-P' which is an
undefined function.
```

This happens because of a problem with the compile-time/load-time semantics, IIUC.

This is the problem, I believe:
1. `extension-event-key-p` is defined normally (i.e., with load time semantics) in input.lisp.
2. `extension-event-key-p` is forward referenced in the `deftype` for `event-key` in clx.lisp.  
3.  Allegro seems to eagerly check some properties of the `event-key` type.  The crash occurs in compiling the defun for `get-external-event-code`, which declares its `event` parameter to be of type `event-key`.  This causes Allegro to invoke an internal function called `normalize-type`, which in turn calls `subtypep-specialist` somehow on the definition of `event-key`, invoking `extension-event-key-p`, which is not yet defined.

```
EXTENSION-EVENT-KEY-P <-
  TYPEP <- (EXCL::SUBTYPEP-SPECIALIST 1 MEMBER) <-
  EXCL:NORMALIZE-TYPE <- COMP::PA-NEW-LISP-TEMP <-
  COMP::PA-PROCESS-LAMBDA-LIST <- COMP::PA-COMPILE-LAMBDA <-
  COMP::PA-START-COMPILE <- COMP::COMPILE-LE <-
  COMP::COMPILE-TO-LAPS <- COMP::COMPILE-FUNCTION-GROUP <-
  COMP::COMPILE-P-DEFUN <- COMP::COMPILE-PROCESS-FORM <-
  (FLET COMPILE-FILE EXCL::CONTINUATION) <- COMPILE-FILE <-
  COMP::WRAP-COMPILE-FILE <-
  ASDF/UTILITY:CALL-WITH-MUFFLED-CONDITIONS <-
  ASDF/LISP-BUILD::CALL-WITH-SAVED-DEFERRED-WARNINGS <-
  ASDF/PATHNAME:CALL-WITH-ENOUGH-PATHNAME <-
  ASDF/LISP-BUILD:COMPILE-FILE* <-
```

I was checking to see if this was Franz's fault, or CLX's, and I think it's CLX's.  Here's the relevant bit from the `deftype` definition in the ANSI Spec:

> If a deftype form appears as a top level form, the compiler must ensure that the name is recognized in subsequent type declarations. The programmer must ensure that the body of a deftype form can be evaluated at compile time if the name is referenced in subsequent type declarations.

This seems problematic, because it requires `extension-event-key-p` to be available at compile-time, which in turn means that the `*extensions*` variable must be defined at compile time, and....

I had a bash at fixing this, but the changes required were too substantial and touched too much code I didn't understand well.  Hoping the solution is obvious to someone else.

**Comment by dkochmanski** [comment]
I think that it is enough to `defvar *extensions*` at all times (wrap in eval-when) and do the same for `extension-event-key-p`. We don't need to have it populated at compile time (and `defvar` won't overwrite already populated values). Could you see if the most recent `develop` https://github.com/sharplispers/clx/tree/develop works for you?

Thank you for a very detailed report.

**Comment by dkochmanski** [comment]
closing now, if still causes a problem please reopen.
