### ISSUE TITLE
demos should not be loaded automatically

### ISSUE THREAD

**Issue by dkochmanski** [sharplispers/clx#69]
currently we include demo files in main distribution in demos module.

**Comment by TeMPOraL** [comment]
Probably causing #78.

**Comment by uint** [comment]
I don't think the demos are loaded together with the entire clx. In the clx.asd file they are defined as members of the example-source-file class, which overrides the perform method so that they're not loaded.

**Comment by TeMPOraL** [comment]
RE #78, they're still compiled, which seems to be causing the problem.

See: https://github.com/sharplispers/clx/blob/33d8c98c76e55945cc2754fff4a3c084d37a7090/input.lisp#L86

The macro `define-extension` spits out code that sets `*extensions*` variable during compile-time.

(Maybe I'm doing things wrong by using CLX in the same Lisp image that compiled it? Is it a standard thing to discard images after compilation?)

**Comment by dkochmanski** [comment]
fixed.
