### ISSUE TITLE
Any chance of a release?

### ISSUE THREAD

**Issue by CMB** [sharplispers/clx#70]
I want to package StumpWM for Void Linux, and Stump depends on CLX.
Void tends to eschew packaging git snapshots.
Any chance of getting a release for CLX?  Please?

**Comment by dkochmanski** [comment]
Sorry for late response. I've bumped version number and added tag which points at it. Also created `stable` branch which has the release. Enough changes has accumulated to wrap a new release already, so I hope there is no controversy in pushing this change.

**Comment by CMB** [comment]
Wonderful!  Thank you very much.

**Comment by dkochmanski** [comment]
Sure. Closing the issue.
