### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by dschoepe** [sharplispers/clx#72]
The link in `README.md` points to https://sharplispers.github.io/clx/ for the manual, but that page doesn't exist.

**Comment by PuercoPop** [comment]
For some reason travis isn't pushing the manual to the [gh-branch](https://github.com/sharplispers/clx/tree/gh-pages). #37

**Comment by TeMPOraL** [comment]
Still missing. Not to mention, the main page (sans "/clx/") is missing too.

**Comment by tpine** [comment]
It appears from looking at the currently active pull request that travis is currently not running. Maybe that's the issue?

**Comment by dkochmanski** [comment]
@luismbo   could you look into this issue?

**Comment by luismbo** [comment]
@dkochmanski this rings a bell. Will look into it.

**Comment by luismbo** [comment]
Fixed in https://github.com/sharplispers/clx/commit/89eed9278e3c9c966de1aa0cb6467c547756c8c3.
