### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by g4jc** [sharplispers/clx#76]
Hello,
I was unable to find the LICENSE file for this program. Please consider adding one so that this can be packaged in various GNU/Linux distros.

List of GPL compatible licenses:
https://www.gnu.org/licenses/license-list.html

**Comment by Jehops** [comment]
I see most files have some legal text at the top and clx.asd has 
> :license "MIT"

I'm not affiliated with the project.

**Comment by dkochmanski** [comment]
excatly, license is MIT, I don't think we need separate file for that
