### ISSUE TITLE
The function XLIB::|Internal-Copy-GCONTEXT-TRAPEZOID-ALIGNMENT| is undefined.

### ISSUE THREAD

**Issue by TeMPOraL** [sharplispers/clx#78]
There's a weird thing happening w/ recompiling vs. just loading CLX.

On a fresh SBCL 1.3.19 the following happens for me:

Rebuilding CLX:
```lisp
CL-USER> (asdf:load-system :clx :force t)
T
CL-USER> xlib::*gcontext-extensions*
(#(:TRAPEZOID-ALIGNMENT :X XLIB::|Internal-Set-GCONTEXT-TRAPEZOID-ALIGNMENT|
   XLIB::|Internal-Copy-GCONTEXT-TRAPEZOID-ALIGNMENT|))
```
But after restarting and loading without rebuilding:
```lisp
CL-USER> (asdf:load-system :clx)
T
CL-USER> xlib::*gcontext-extensions*
NIL
```

In both cases:
```lisp
CL-USER> (describe 'XLIB::|Internal-Copy-GCONTEXT-TRAPEZOID-ALIGNMENT|)
XLIB::|Internal-Copy-GCONTEXT-TRAPEZOID-ALIGNMENT|
  [symbol]
; No value
```

i.e. the symbol is in particular not fbound. The entry in `*gcontext-extensions*` is, however, used later by CLX via funcall, resulting in the reported error.

The problem disappears (i.e. `*gcontext-extensions*` stays `NIL` after recompiling CLX) when I comment out loading `demo/zoid.lisp` and `test/trapezoid.lisp` in the ASD file, which suggests it's the zoid demo that's interfering with compilation of the library.

**Comment by uint** [comment]
The demo and test files don't seem to be loaded automatically. As far as I can tell, the problem is that demo/zoid.lisp expands the `define-gcontext-accessor` macro during compilation, like so:

```
(define-gcontext-accessor trapezoid-alignment :default :x
  :set-function set-trapezoid-alignment)
```

The `define-gcontext-accessor` macro definition (in gcontext.lisp) has this `eval-when` block:
```
(eval-when (:compile-toplevel :load-toplevel :execute)
	 (defparameter ,internal-state-index
		       (add-gcontext-extension ',key-name ,default ',internal-set-function
					       ',internal-copy-function))
	 ) ;; end eval-when
```

I have no idea what to do with this, though. Just removing :compile-toplevel makes the whole thing fail to build.

**Comment by TeMPOraL** [comment]
My vote is to move demos and tests into separate systems (the latter [probably depending on the former](https://github.com/sharplispers/clx/blob/d814fb50c18b846e48fcafa9166879fc5b201dc4/clx.asd#L106)) - this way demos and tests will never unexpectedly pollute the Lisp image used to compile the CLX proper.

**Comment by dkochmanski** [comment]
fixed.
