### ISSUE TITLE
Versioning question

### ISSUE THREAD

**Issue by Jehops** [sharplispers/clx#82]
Thanks for adopting clx.  The FreeBSD clx package has been using https://common-lisp.net/~abridgewater/dist/clx/clx-0.7.4.tgz, but we would like to switch to your release.  One issue is that your newer code is versioned lower.  Our packaging tools have ways to deal with a newer release with a lower version, but there are downsides.  Do you have plans to tag a new version in the not-too-distant future?  That would be helpful for us to get your code package.

**Comment by dkochmanski** [comment]
we can bump release number to 0.7.5 I think, that shouldn't be much of a problem. See `stable` branch for stable version.

**Comment by dkochmanski** [comment]
when we have merged testing suite (see PRs), I'll bump the version unless someone raises argument against that.

**Comment by Jehops** [comment]
Thank you.  Even bumping to version 0.7.4 would work (for us).

**Comment by dkochmanski** [comment]
OK, bumped to 0.7.4, please pull `stable` branch.

**Comment by Jehops** [comment]
Thanks.  Is it possible to tag the 0.7.4 release?  It still lists 0.7.3 as the last one.

The tags are what our ports framework uses.  `DISTVERSION=0.7.4` will download the tarball for the commit associated with the release.

**Comment by dkochmanski** [comment]
I forgot to push tags, my bad.
