### ISSUE TITLE
Bump version to 0.7.5

### ISSUE THREAD

**Issue by nimiux** [sharplispers/clx#95]
Any plans of bumping the package version to 0.7.5?

[Stumpwm Gentoo ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-wm/stumpwm/stumpwm-1.0.1_rc.ebuild) builds fine with the current master branch but fails with version 0.7.4. It would be easy for us if the version is bumped.

Thanks.

**Comment by dkochmanski** [comment]
Done (see branch stable or tag 0.7.5). Note that next release will be probably 0.8.0 because of major code change from #91.

**Comment by nimiux** [comment]
That was quick! Thanks a bunch!
